# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 3b7f14f022d15a49d48ccef185da6afe558cc8914c8d08b5008c5cb1fb16c7e983b6c7d2e30959cb9d212cff5f7840e6fd28745af71b41a3617d0e96944ba2f2

test:
  secret_key_base: bfea57f323e0b7291e623c55138d9712dbff4d1a64dd04d3d2f9bea90042c75fd72fdb981fdfe592755f13b165a6804efe742d1c22a36454931e800ec124aca6

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
